Added setRetroMake to fix #1
MaxStrange/retrowrapper pull request #2
Opened 2018-05-22 00:47 UTC by frenchie4111

2018-05-22 13:46 UTC, frenchie4111 commented
Usage:
```
import retrowrapper
from retro_contest.local import make
retrowrapper.setRetroMake( make )
env1 = retrowrapper.RetroWrapper(
    game='SonicTheHedgehog2-Genesis', 
    state='MetropolisZone.Act1'
)
env2 = retrowrapper.RetroWrapper(
    game='SonicTheHedgehog2-Genesis', 
    state='MetropolisZone.Act2'
)
```

2018-05-22 23:01 UTC, MaxStrange requested changes
Cool. Could you also update the README with an additional example with the new usage?

2018-05-22 23:01 UTC, MaxStrange commented on retrowrapper.py
> +def setRetroMake( new_retro_make_func ):
Please rename to 'set_retro_make'

2018-05-22 23:01 UTC, MaxStrange commented on retrowrapper.py
> +import time
Remove unused import

2018-05-22 23:51 UTC, frenchie4111 commented
Changes complete

2018-05-23 02:54 UTC, MaxStrange approved these changes

2018-05-23 02:54 UTC, merged